### ISSUE TITLE
Don't use hyphens

### ISSUE THREAD

**Issue by Paratron** [timche/postcss-german-stylesheets#11]
Reading things like "schrift-größe" and "hintergrund-farbe" really hurts.
German has wonderful worlds like "Schriftgröße" and "Hintergrundfarbe". We should really get rid of the hyphens here.

Other things like "außenabstand-unten" make sense.

**Comment by timche** [comment]
Valid issue. 

Is the first character to be in uppercase intended because they are nouns, so they also should be written like that?

**Comment by timche** [comment]
I've resolved this issue with https://github.com/timche/postcss-german-stylesheets/commit/0769c310786aab41b63a7d42446d320ffe8a2378.
