### ISSUE TITLE
Auto. Documentation

### ISSUE THREAD

**Issue by ntwcklng** [timche/postcss-german-stylesheets#7]
What do you guys think?

`````` javascript
var _ = require('lodash');
var fs = require('fs');
var plugin = require('./');

var properties = "# Properties \n";
var values = "# Values \n";
var overview = "";
var file = "overview.md";

_.forEach(plugin.mapProperties, function(value, key) {
    properties += "\n### " + key + ":\n```\n" + value + "\n``` \n\n"; // (╯°□°）╯︵ ┻━┻
});
_.forEach(plugin.mapValues, function(value, key) {
    values += "\n### " + key + ":\n```\n" + value + "\n``` \n\n";
});
overview = properties + values;

fs.writeFile(file, overview, function(error) {
    if(error) {
        console.log(error);
    }
    console.log("done");
});
``````

Add this to the build process and we get a nice automated documentation which looks like this:
# Properties
### background-color:

```
hintergrund-farbe
```
### background-image:

```
hintergrund-bild
```
### background-position:

```
hintergrund-position
```
### background-repeat:

```
hintergrund-wiederholung
```
### background:

```
hintergrund
```

**Comment by timche** [comment]
That's a nice feature! I actually wanted to create a static site for this project. I've already created a `gh-pages` branch. Would be nice, if we could implement it there in the docs like [Bourbon Docs](http://bourbon.io/docs/).

**Comment by ntwcklng** [comment]
Okay. If we use Jekyll, its straightforward to include such a generated markdown file :+1:

**Comment by timche** [comment]
Yep, we will use Jekyll.

**Comment by timche** [comment]
Done in https://github.com/timche/postcss-german-stylesheets/commit/6283b247e5467ebe3c82ce45585b9ba23f8c1be8
