### ISSUE TITLE
Properties which are nouns should have an uppercase first letter

### ISSUE THREAD

**Issue by voodoocode** [timche/postcss-german-stylesheets#9]
In german all the nouns are written with an uppercase first letter, no matter if in the middle of a sentence or at the beginning.
So all the properties which are nouns (all the keyword like border, position) should be begin with a uppercase letter, but not adjectives (like colors), prepositions (right, bottom).

The example from the readme would be:

```
.foo {
    Höhe: 300px;
    Außenabstand-unten: 10px;  //unten: preposition: lower
    Schrift-Größe: 20px !wichtig; //difficult case, as adjective it would be lowercased, as exclamation 'Wichtig'
    Hintergrund-Farbe: schwarz; //schwarz: adjective: lower
    Farbe: weiß;
}
```

What do you think?

**Comment by timche** [comment]
I think this would cause much confusion what to write in uppercase and lowercase. It's easier to stick to lowercase.
